# .github/workflows/release.yml
name: Release

on:
  push:
    branches: ["main"]

jobs:
  build-jar:
    uses: ./.github/workflows/build.yml
    with:
      runner: ubuntu-latest
      artifact-name: jar
      artifact-path: target/*.jar

  build-windows-launcher:
    uses: ./.github/workflows/build.yml
    with:
      runner: windows-latest
      artifact-name: windows-exe
      artifact-path: target/*.exe

  release:
    needs: [build-jar, build-windows-launcher]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          java-version: "25"
          distribution: temurin
      - uses: actions/download-artifact@v4
        with:
          path: release-files
      - name: Extract version
        id: get-version
        run: |
          echo "version=$(mvn -q help:evaluate \
            -Dexpression=project.version \
            -DforceStdout)" >> "$GITHUB_OUTPUT"
      - uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
          files: release-files/**/*
          generate_release_notes: true